# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  host: localhost
  port: 5432
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  user: gagan
  password:

development:
  <<: *default
  database: atlint_dev

test:
  <<: *default
  database: atlint_test
